### ISSUE TITLE
First time start error

### ISSUE THREAD

**Issue by Climenty** [earvingad/LaunchCold#1]
Log:

```
Hidden imported:  set([])
Favorites imported:  set([])
Compositing False
ocurrio un problema
Traceback (most recent call last):
  File ".launchcold/launchcold", line 1161, in <module>
    launcher = launchcold()
  File ".launchcold/launchcold", line 954, in __init__
    self.init_window()
  File ".launchcold/launchcold", line 1094, in init_window
    apps = AppStore(mainbox, self)
  File ".launchcold/launchcold", line 226, in __init__
    categories = self.getCategories()
  File ".launchcold/launchcold", line 886, in getCategories
    root = etree.parse(self.appsmenu)
  File "lxml.etree.pyx", line 3201, in lxml.etree.parse (src/lxml/lxml.etree.c:65033)
  File "parser.pxi", line 1571, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:93221)
  File "parser.pxi", line 1600, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:93508)
  File "parser.pxi", line 1500, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:92565)
  File "parser.pxi", line 1047, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:89449)
  File "parser.pxi", line 577, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:84831)
  File "parser.pxi", line 676, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:85936)
  File "parser.pxi", line 616, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:85258)
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: menu line 261 and xdg-menu, line 262, column 12
```

**Comment by earvingad** [comment]
Seems like the program was still looking for categories.
It should be fixed now. Can you confirm?

**Comment by Climenty** [comment]
Yes, this error is gone.
The next one looks like:

```
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
launchcold:1042: Warning: invalid (NULL) pointer instance
  self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
launchcold:1042: Warning: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
launchcold:1053: GtkWarning: IA__gdk_screen_is_composited: assertion 'GDK_IS_SCREEN (screen)' failed
  if not self.window.is_composited():
launchcold:1070: GtkWarning: IA__gdk_screen_is_composited: assertion 'GDK_IS_SCREEN (screen)' failed
  print 'Compositing %s' % self.window.is_composited()
launchcold:536: GtkWarning: IA__gdk_screen_get_width: assertion 'GDK_IS_SCREEN (screen)' failed
  maxcolums = gtk.gdk.screen_width() / (ICON_SIZE + COL_PADDING
launchcold:543: GtkWarning: IA__gdk_screen_get_height: assertion 'GDK_IS_SCREEN (screen)' failed
  maxrows = gtk.gdk.screen_height() / (ICON_SIZE * 2
launchcold:451: GtkWarning: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  button = gtk.Button(_(' All '))
launchcold:451: Warning: g_object_get: assertion 'G_IS_OBJECT (object)' failed
  button = gtk.Button(_(' All '))
launchcold:468: GtkWarning: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  button = gtk.Button(_(' Favorites '))
launchcold:468: Warning: g_object_get: assertion 'G_IS_OBJECT (object)' failed
  button = gtk.Button(_(' Favorites '))
launchcold:551: GtkWarning: IA__gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  theme = gtk.icon_theme_get_default()
Traceback (most recent call last):
  File "launchcold", line 1148, in <module>
    launcher = launchcold()
  File "launchcold", line 941, in __init__
    self.init_window()
  File "launchcold", line 1081, in init_window
    apps = AppStore(mainbox, self)
  File "launchcold", line 250, in __init__
    self.add_toolbar(mainbox, launcher)
  File "launchcold", line 490, in add_toolbar
    , 24))
  File "launchcold", line 556, in get_icon
    pixbuf = theme.load_icon('exec', size, 0)
AttributeError: 'NoneType' object has no attribute 'load_icon'
```

But it may be due to the fact that I tryed it through remote (X2Go) client.
